### ISSUE TITLE
change name to dicomweb-client-js

### ISSUE THREAD

**Issue by pieper** [dcmjs-org/dicomweb-client#14]
@hackermd @swederik @emelalkim - any objections or comments?

Now that we have [dicomweb-server-js](https://github.com/dcmjs-org/dicomweb-server-js) underway in dcmjs-org, it would be nice to have naming symmetry between the client and server.

In addition, the name dicomweb-client is already used for the [python version](https://github.com/clindatsci/dicomweb-client).  @hackermd and I decided at the start that it was odd to use the same name for two different implementations but we did it anyway.  Now I want to reverse that decision.

So on balance I think it's better to rename the client to match the server.

**Comment by hackermd** [comment]
I always find it bit weird to include the name of the language in a language-specific package and thus object to renaming the npm package. I would further prefer if npm package and repository would have the same name. Therefore, I would keep the name `dicomweb-client`.

I don't think it's a problem that the two repositories, which hold Python and JavaScript client implementations, have the same name, since they reside under a different global name space. The Python package is installed via the pip package manager and the JavaScript version is installed via the npm package manager. Therefore, I don't anticipate any name space collision, do you?

Why not just use `dicomweb-server` for the server to match the existing pattern? The name space `dcmjs-org` already indicates that repositories contain JavaScript implementations.

**Comment by emelalkim** [comment]
Hi, I am open to changing the server's name to dicomweb-server. The reason I chose to put js to the end was because of the exact issue Steve is talking about. I was searching github for related projects, got confused and wanted to make the name as clear and expressive as possible. But as we moved the project under dcmjs-org, may be we don't need js part anymore

**Comment by pieper** [comment]
I like the symmetry of dicomweb-server and dicomweb-client, so I'd be happy with that.  Thanks.
